# Generated by Django 5.0.1 on 2024-01-25 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='code',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999, message='Код должен быть 4-значным числом'), django.core.validators.MinValueValidator(1000, message='Код должен быть 4-значным числом')], verbose_name='Код подтверждения'),
        ),
    ]
