# Generated by Django 5.0.1 on 2024-01-27 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautySaloon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Чаевые'),
        ),
    ]
