# Generated by Django 5.0.1 on 2024-01-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautySaloon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Телефон')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Вопрос')),
            ],
        ),
    ]
