# Generated by Django 5.0.1 on 2024-01-27 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BeautySaloon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='order',
            name='saloon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='BeautySaloon.saloon', verbose_name='Салон'),
        ),
        migrations.AddField(
            model_name='saloon',
            name='service',
            field=models.ManyToManyField(related_name='saloons', to='BeautySaloon.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='BeautySaloon.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='BeautySaloon.servicecategory', verbose_name='Категория сервиса'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='saloon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='BeautySaloon.saloon', verbose_name='Салон'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='service',
            field=models.ManyToManyField(related_name='specialists', to='BeautySaloon.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='review',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='BeautySaloon.specialist', verbose_name='Специалист'),
        ),
        migrations.AddField(
            model_name='order',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='BeautySaloon.specialist', verbose_name='Специалист'),
        ),
    ]
