# Generated by Django 5.0.1 on 2024-01-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautySaloon', '0003_remove_specialist_service_order_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата отзыва'),
        ),
    ]
