# Generated by Django 5.0.1 on 2024-01-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautySaloon', '0003_advertising_slug_alter_order_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Уникальная часть url'),
        ),
    ]
