# Generated by Django 5.0.1 on 2024-01-29 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautySaloon', '0003_alter_consultationrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата отзыва'),
            preserve_default=False,
        ),
    ]
